Repository 902z/gheupPAY, pull requests merged in 2024-06, with the labels that each got.

#1 📝 docs: Create issue templates
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/✨-feat.md
  .github/ISSUE_TEMPLATE/🐛-fix.md
  .github/ISSUE_TEMPLATE/💄-ui.md
  .github/ISSUE_TEMPLATE/📝-docs.md
  .github/ISSUE_TEMPLATE/📦-chore.md
Labels: 📝 docs

#4 🎉 init: 프로젝트 초기 세팅
  .eslintrc.json
  .gitignore
  .prettierrc
  LICENSE
  README.md
  app/layout.tsx
  app/page.tsx
  next.config.mjs
  package.json
  postcss.config.mjs
  styles/globals.css
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: 📦 chore

#6 ✨ feat: 테일윈드 색상 변수 설정
  tailwind.config.ts
Labels: ✨ feat

#14 📦 chore: 이미지, 아이콘 삽입
  public/icons/alert-allowed.png
  public/icons/alert-rejected.png
  public/icons/arrow-up-gray-20.png
  public/icons/arrow-up-red-40.png
  public/icons/arrow-up-white.png
  public/icons/camera.png
  public/icons/check.png
  public/icons/clock.png
  public/icons/close.png
  public/icons/dropdown-down.png
  public/icons/dropdown-up.png
  public/icons/facebook.png
  public/icons/instagram.png
  public/icons/mail.png
  public/icons/map-pin.png
  public/icons/noti-active.png
  public/icons/noti-none.png
  public/icons/phone.png
  public/icons/search.png
  public/icons/warning.png
  public/images/logo.png
Labels: 📦 chore

#18 📦 chore: primarycolor 추가
  tailwind.config.ts
Labels: 📦 chore

#25 🐛 fix: admin url 추가
  app/(route)/admin/announce-create/page.tsx
  app/(route)/admin/announce-detail/page.tsx
  app/(route)/admin/store-detail/page.tsx
  app/(route)/admin/store-edit/page.tsx
  app/(route)/admin/store-register/page.tsx
Labels: 🐛 fix

#15 ✨ feat: custom text input 컴포넌트
  app/components/custom-text-input/index.tsx
  package.json
  styles/globals.css
  yarn.lock
Labels: ✨ feat

#21 💄 ui: 공고 카드 컴포넌트 구현
  app/(route)/(alba)/announce-list/_components/announce-card/index.tsx
  app/(route)/(alba)/announce-list/page.tsx
  tailwind.config.ts
Labels: 💄ui

#28 ✨ feat: 시급 라벨 구현
  _constants/MINIMUN_HOURLY_WAGE.ts
  _util/calculate-wage-percentage .ts
  app/(route)/(alba)/announce-list/_components/announce-card/index.tsx
  app/components/label-hourly-rate/index.tsx
  public/icons/arrow-up-red-40.png
  public/icons/arrow-up-white.png
Labels: ✨ feat

#39 🚚 chore: 폴더명 변경 및 폴더 이동
  app/(route)/(alba)/announce-list/_components/announce-card/index.tsx
  app/_apis/api.ts
  app/_components/button/index.tsx
  app/_components/custom-text-input/index.tsx
  app/_components/label-hourly-rate/index.tsx
  app/_components/label-status/index.tsx
  app/_components/list-card/index.tsx
  app/_components/modal/index.tsx
  app/_components/pagination/index.tsx
  app/_constants/MINIMUN_HOURLY_WAGE.ts
  app/_hooks/useExample.tsx
  app/_util/calculate-wage-percentage .ts
Labels: 📦 chore

#27 ✨ feat: 메타데이터 추가
  app/(route)/(alba)/announce-detail/page.tsx
  app/(route)/(alba)/profile-detail/page.tsx
  app/(route)/(alba)/profile-register/page.tsx
  app/(route)/admin/announce-create/page.tsx
  app/(route)/admin/announce-detail/page.tsx
  app/(route)/admin/store-detail/page.tsx
  app/(route)/admin/store-edit/page.tsx
  app/(route)/admin/store-register/page.tsx
  app/layout.tsx
  app/not-found.tsx
  public/icons/favicon.png
Labels: ✨ feat

#30 📦 chore: 전체 페이지 컨테이너 컴포넌트 적용
  app/layout.tsx
Labels: 📦 chore

#36 💄 ui: 상세 필터 컴포넌트 구현
  app/(route)/(alba)/announce-list/_components/filter/index.tsx
  app/(route)/(alba)/announce-list/page.tsx
  constants/address.ts
  public/icons/close-red-40.png
  public/icons/close.png
  styles/globals.css
Labels: 💄ui

#32 ✨ feat: 공통 버튼 컴포넌트
  app/_components/button/index.tsx
Labels: ✨ feat

#41 ✨ feat: 전역 상태 관리 (로그인 부분)
  app/_components/test.tsx
  app/_hooks/useStore.tsx
  app/layout.tsx
  stores/user-store.ts
Labels: ✨ feat

#34 💄 ui: 로그인/회원가입 ui 구현
  app/(route)/(login)/_utils/schema.ts
  app/(route)/(login)/layout.tsx
  app/(route)/(login)/login/page.tsx
  app/(route)/(login)/signup/_components/user-type-radio/index.tsx
  app/(route)/(login)/signup/_components/user-type-select/index.tsx
  app/(route)/(login)/signup/page.tsx
  app/_components/button/index.tsx
  app/_components/custom-text-input/index.tsx
  app/_constants/MINIMUN_HOURLY_WAGE.ts
  app/_constants/minimum-hourly-wage.ts
  app/_constants/user-type.ts
  app/_constants/validation-text.ts
  app/_util/calculate-wage-percentage .ts
  public/icons/check.png
  public/icons/uncheck.png
  tailwind.config.ts
Labels: 💄ui

#33 ✨ feat: 입력폼 드롭다운 컴포넌트
  app/(route)/admin/store-register/layout.tsx
  app/(route)/admin/store-register/page.tsx
  app/_components/form-dropdown/index.tsx
  app/_constants/validation-text.ts
  app/_hooks/use-outside-click.ts
  public/icons/down-arrow.png
  public/icons/up-arrow.png
  styles/globals.css
Labels: ✨ feat

#45 ✨ feat: 공고 리스트 페이지 구현
  .gitignore
  .prettierrc
  app/(route)/(alba)/announce-list/_components/all-announce-card/index.tsx
  app/(route)/(alba)/announce-list/_components/announce-card/index.tsx
  app/(route)/(alba)/announce-list/_components/customized-announce-card/index.tsx
  app/(route)/(alba)/announce-list/page.tsx
  app/_apis/api.ts
  app/_components/label-hourly-rate/index.tsx
  app/_lib/axios.ts
  app/_util/calculate-time-range.ts
  app/_util/calculate-wage-percentage .ts
  app/_util/date-format.ts
  app/_util/number-format.ts
  app/layout.tsx
  next.config.mjs
  package.json
  public/icons/clock.png
  public/icons/map-pin.png
  styles/globals.css
  yarn.lock
Labels: ✨ feat

#51 ♻️ refactor: 공고 카드 컴포넌트 분리
  app/(route)/(alba)/announce-list/_components/all-announce-card/index.tsx
  app/(route)/(alba)/announce-list/_components/customized-announce/index.tsx
  app/(route)/(alba)/announce-list/page.tsx
  app/_components/announce-card/index.tsx
Labels: ♻️ refactor

#53 ✨ feat : 헤더, 푸터 반응형 ui, 상태에 따른 조건부 렌더링, 전역 상태 연결
  app/(route)/(alba)/announce-list/_components/filter/index.tsx
  app/(route)/(login)/layout.tsx
  app/_components/footer/index.tsx
  app/_components/header/_component/header-login.tsx
  app/_components/header/_component/header-not-login.tsx
  app/_components/header/_component/header-selector.tsx
  app/_components/header/_component/search-bar.tsx
  app/_components/header/index.tsx
  app/_components/test.tsx
  app/_constants/address.ts
  app/_hooks/use-store.tsx
  app/_hooks/useExample.tsx
  app/layout.tsx
  app/page.tsx
  public/icons/facebook.png
  public/icons/instagram.png
  public/icons/mail.png
  public/icons/noti-active.png
  stores/create-store.ts
Labels: ✨ feat

#61 ♻️ refactor : 전역 상태 관리 기능 정리 (user_id 제거, 최근 본 공고 저장 기능 추가)
  app/(route)/(login)/login/page.tsx
  app/_components/header/_component/header-login.tsx
  app/_components/header/_component/header-not-login.tsx
  app/_components/header/_component/header-selector.tsx
  app/_components/hydration/index.tsx
  app/_hooks/use-store.tsx
  app/layout.tsx
  stores/create-store.ts
Labels: ♻️ refactor

#62 ✨ feat: 내 가게 상세 페이지 구현
  app/(route)/(login)/login/page.tsx
  app/(route)/(login)/signup/page.tsx
  app/(route)/admin/shop-register/page.tsx
  app/(route)/admin/store-detail/[shop_id]/page.tsx
  app/(route)/admin/store-detail/_components/my-store-detail-card/index.tsx
  app/(route)/admin/store-detail/_components/none-notice/index.tsx
  app/_apis/shop/index.ts
  app/_apis/type/index.ts
  app/_components/button/index.tsx
  public/.gitkeep
Labels: ✨ feat

#57 ✨ feat: 페이지네이션 구현
  app/(route)/(alba)/notice-list/_components/customized-notice/index.tsx
  app/(route)/(alba)/notice-list/page.tsx
  app/_apis/notice/index.ts
  app/_apis/notice/response-type.ts
  app/_components/notice-card/index.tsx
  app/_components/notice-list/index.tsx
  app/_components/pagination/index.tsx
  public/icons/arrow-left-disabled.png
  public/icons/arrow-left.png
  public/icons/arrow-right.png
  styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: ✨ feat, ♻️ refactor

#47 ✨ feat: 로그인/회원가입 기능 구현
  app/(route)/(login)/layout.tsx
  app/(route)/(login)/login/loading.tsx
  app/(route)/(login)/login/page.tsx
  app/(route)/(login)/schema.ts
  app/(route)/(login)/signup/loading.tsx
  app/(route)/(login)/signup/page.tsx
  app/_apis/authentication/index.ts
  app/_apis/instances.ts
  app/_apis/user/index.ts
  app/_constants/error-message.ts
  app/_hooks/useCheckLoginStatus.ts
  app/_util/cookie.ts
  app/page.tsx
  public/icons/pulse.svg
Labels: ✨ feat

#66 ✨ feat: 특정 가게의 특정 공고 상세 페이지 구현
  app/(route)/admin/notice-detail/[notice_id]/page.tsx
  app/(route)/admin/notice-detail/_components/notice-detail-card/index.tsx
  app/(route)/admin/notice-detail/_components/only-label-hourly-rate/index.tsx
  app/(route)/admin/notice-detail/page.tsx
  app/(route)/admin/shop-detail/[shop_id]/page.tsx
  app/(route)/admin/shop-detail/_components/my-shop-detail-card/index.tsx
  app/(route)/admin/shop-detail/_components/none-notice/index.tsx
  app/(route)/admin/shop-detail/page.tsx
  app/_apis/shop/index.ts
  app/_apis/type/index.ts
  styles/globals.css
Labels: ✨ feat

#75 ✨ feat : 로그인/회원가입 모달 적용
  app/(route)/(login)/layout.tsx
  app/(route)/(login)/login/login-form.tsx
  app/(route)/(login)/login/page.tsx
  app/(route)/(login)/signup/page.tsx
  app/(route)/(login)/signup/sign-up-from.tsx
  app/(route)/admin/shop-register/layout.tsx
  app/(route)/admin/shop-register/page.tsx
  app/_apis/instances.ts
  app/_components/custom-price-input/index.tsx
  app/_components/custom-textarea/index.tsx
  app/_components/modals/_components/confirm-modal.tsx
  app/_components/modals/_components/open-modal.tsx
  app/_components/modals/_components/select-modal.tsx
  app/_components/modals/_components/warning-modal.tsx
  app/_components/modals/_components/window-modal.tsx
  app/_components/modals/index.tsx
  app/_components/title-with-x/index.tsx
  app/_hooks/use-check-login-status.ts
  app/_hooks/use-modal.ts
  app/page.tsx
Labels: ✨ feat

#77 ♻️ refactor: 카드 클릭시 해당 공고 페이지로 이동
  app/(route)/(alba)/notice-detail/[shop_id]/[notice_id]/page.tsx
  app/(route)/(alba)/notice-list/_components/customized-notice/index.tsx
  app/_components/notice-card/index.tsx
  app/_components/notice-detail-card/index.tsx
Labels: ♻️ refactor

#74 ♻️ refactor : 헤더, 버튼 리팩토링
  app/(route)/admin/shop-detail/_components/none-notice/index.tsx
  app/_components/button/index.tsx
  app/_components/header/index.tsx
  app/_components/modals/_components/confirm-modal.tsx
  app/_components/modals/_components/select-modal.tsx
  app/_components/shop-register/index.tsx
Labels: ♻️ refactor
