Repository 902z/gheupPAY, pull requests merged in 2024-07, with the labels that each got.

#80 ✨ feat: 모달 스크롤 막기
  app/_components/button/index.tsx
  app/_components/modals/_components/confirm-modal.tsx
  app/_components/modals/_components/select-modal.tsx
  app/_components/modals/_components/warning-modal.tsx
  app/_hooks/use-modal.ts
  app/page.tsx
  styles/globals.css
Labels: ✨ feat

#84 ✨ feat : 사용자에 따른 리다이렉션 처리 구현
  app/_apis/authentication/index.ts
  middleware.ts
Labels: ✨ feat

#82 ♻️ refactor : 최근 본 공고 리스트 리팩토링 (최근 본 공고 리스트 관련 전역 상태 로직 변경, 타입 파일 생성)
  app/(route)/(alba)/notice-detail/_components/recent-notices/index.tsx
  app/(route)/(alba)/notice-list/_components/customized-notice/index.tsx
  app/(route)/admin/shop-detail/_components/my-shop-detail-card/index.tsx
  app/_apis/notice/response-type.ts
  app/_apis/shop/index.ts
  app/_apis/type/index.ts
  app/_components/notice-card/index.tsx
  app/_components/notice-card/skeleton.tsx
  app/_components/notice-detail-card/index.tsx
  app/_components/notice-list/index.tsx
  app/page.tsx
  stores/create-store.ts
Labels: ♻️ refactor

#86 ✨ feat: status에 따른 라벨 구현 및 테이블 컬럼 고정
  app/(route)/admin/notice-detail/[notice_id]/page.tsx
  app/(route)/admin/notice-detail/_components/alba-application-table/index.tsx
  app/(route)/admin/notice-detail/_components/status-label/index.tsx
  app/_apis/application/index.ts
  app/_components/notice-detail-card/index.tsx
Labels: ✨ feat

#85 ✨ feat: 상세 필터 구현
  app/(route)/(alba)/notice-list/_components/filter/index.tsx
  app/(route)/(alba)/notice-list/page.tsx
  app/_apis/notice/index.ts
  app/_components/notice-list/index.tsx
  app/_util/get-now.ts
  package.json
  styles/globals.css
  yarn.lock
Labels: ✨ feat

#91 ✨ feat: 404 페이지 구현
  app/not-found.tsx
  public/images/404.png
Labels: ✨ feat

#88 ✨ feat: 내 프로필 페이지 구현
  app/(route)/(alba)/profile-detail/_components/alba-status-label/index.tsx
  app/(route)/(alba)/profile-detail/_components/none-application/index.tsx
  app/(route)/(alba)/profile-detail/_components/notice-application-table/index.tsx
  app/(route)/(alba)/profile-detail/_components/user-profile/index.tsx
  app/(route)/(alba)/profile-detail/page.tsx
  app/_apis/application/index.ts
  app/_apis/type/index.ts
  app/_apis/user/index.ts
  app/_lib/axios.ts
  public/icons/phone.png
Labels: ✨ feat

#93 ✨ feat :가게 등록 페이지 parellel routes
  app/(route)/(login)/login/login-form.tsx
  app/(route)/admin/@modal/(.)notice-create/page.tsx
  app/(route)/admin/@modal/(.)notice-create/schema.ts
  app/(route)/admin/@modal/(.)shop-create/page.tsx
  app/(route)/admin/@modal/default.tsx
  app/(route)/admin/layout.tsx
  app/(route)/admin/notice-create/page.tsx
  app/(route)/admin/shop-create/layout.tsx
  app/(route)/admin/shop-create/page.tsx
  app/(route)/admin/shop-create/schema.ts
  app/(route)/admin/shop-create/shop-create-form.tsx
  app/(route)/admin/shop-detail/_components/none-notice/index.tsx
  app/(route)/admin/shop-detail/page.tsx
  app/(route)/admin/shop-register/page.tsx
  app/(route)/admin/shop-register/schema.ts
  app/_components/custom-date-input/index.tsx
  app/_components/custom-time-input/index.tsx
  app/_components/header/_component/header-login.tsx
  app/_components/modals/index.tsx
  app/_components/page-modal/index.tsx
  app/_components/title-with-x/index.tsx
Labels: ✨ feat

#107 ✨ feat: 가게 등록 완성
  app/(route)/(login)/login/login-form.tsx
  app/(route)/(login)/signup/sign-up-from.tsx
  app/(route)/admin/shop-create/schema.ts
  app/(route)/admin/shop-create/shop-create-form.tsx
  app/_apis/shop/index.ts
  app/_apis/type/index.ts
  app/_components/custom-form-dropdown/index.tsx
  app/_components/custom-price-input/index.tsx
  app/_components/modals/index.tsx
  app/_components/page-modal/index.tsx
  app/_constants/address.ts
  app/_constants/category.ts
Labels: ✨ feat

#111 ✨ feat: 검색 기능 구현
  app/(route)/(alba)/notice-list/_components/filter/index.tsx
  app/(route)/(alba)/notice-list/page.tsx
  app/_components/header/_component/search.tsx
  app/_components/header/index.tsx
  app/_components/notice-card/index.tsx
  app/_components/notice-list/index.tsx
  public/icons/close-gray-40.png
  styles/globals.css
Labels: ✨ feat

#108 ✨ feat: 로그인/회원가입 리다이렉트 모달 + 주소도 쿠키에 저장
  app/(route)/(login)/login/login-form.tsx
  app/(route)/(login)/signup/sign-up-from.tsx
  app/(route)/admin/layout.tsx
  app/_apis/authentication/index.ts
  app/_hooks/use-check-login-status.ts
Labels: ✨ feat

#117 ✨ feat: 내 프로필 등록 구현
  app/(route)/(alba)/@modal/(.)profile-register/page.tsx
  app/(route)/(alba)/@modal/default.tsx
  app/(route)/(alba)/layout.tsx
  app/(route)/(alba)/profile-register/_components/form.tsx
  app/(route)/(alba)/profile-register/_components/schema.ts
  app/(route)/(alba)/profile-register/page.tsx
  app/_apis/user/index.ts
  app/_components/custom-form-dropdown/index.tsx
  app/_components/toast/toastProvider.tsx
  app/_util/notification.ts
  app/layout.tsx
  package.json
  yarn.lock
Labels: ✨ feat

#115 ✨ feat: 테이블 pending상태 버튼 클릭시 모달 띄우고 put 요청으로 상태 바꾸기
  app/(route)/(alba)/profile-detail/_components/alba-status-label/index.tsx
  app/(route)/(alba)/profile-detail/_components/notice-application-table/index.tsx
  app/(route)/(alba)/profile-detail/_components/user-profile/index.tsx
  app/(route)/(alba)/profile-detail/page.tsx
  app/(route)/admin/notice-detail/[notice_id]/page.tsx
  app/(route)/admin/notice-detail/_components/alba-application-table/index.tsx
  app/(route)/admin/notice-detail/_components/status-label/index.tsx
  app/_apis/application/index.ts
  app/_components/pagination/index.tsx
  styles/globals.css
Labels: ✨ feat

#97 ✨ feat: 공고 등록페이지 구현
  app/(route)/(login)/signup/sign-up-from.tsx
  app/(route)/admin/@modal/(.)notice-create/_components/index.tsx
  app/(route)/admin/@modal/(.)notice-create/_components/schema.ts
  app/(route)/admin/@modal/(.)notice-create/page.tsx
  app/(route)/admin/layout.tsx
  app/(route)/admin/notice-create/page.tsx
  app/(route)/admin/notice-create/schema.ts
  app/(route)/admin/shop-detail/[shop_id]/page.tsx
  app/(route)/admin/shop-detail/_components/my-shop-detail-card/index.tsx
  app/(route)/admin/shop-detail/_components/none-notice/index.tsx
  app/(route)/admin/shop-detail/page.tsx
  app/_apis/notice/index.ts
  app/_apis/shop/index.ts
  app/_apis/type/index.ts
  app/_apis/user/index.ts
  app/_components/custom-date-input/index.tsx
  app/_components/custom-time-input/index.tsx
  app/_components/header/index.tsx
  app/_components/notice-card/index.tsx
  styles/globals.css
Labels: ✨ feat

#122 ✨ feat: 맞춤 공고 조건에 따라 다르게 제공
  app/(route)/(alba)/notice-list/page.tsx
  app/_components/notice-list/index.tsx
  public/images/blured-custome-desktop.png
  public/images/blured-custome-mobile.png
  yarn.lock
Labels: ✨ feat

#124 ♻️ refactor : 공고 상세 리팩토링 (전역 상태 관리 제거)
  .gitignore
  app/(route)/(alba)/notice-detail/[shop_id]/[notice_id]/page.tsx
  app/(route)/(alba)/notice-detail/_components/recent-notices/index.tsx
  app/(route)/(alba)/notice-list/_components/filter/index.tsx
  app/(route)/(alba)/profile-register/_components/form.tsx
  app/(route)/(login)/login/login-form.tsx
  app/(route)/admin/notice-detail/[notice_id]/page.tsx
  app/_actions/index.ts
  app/_apis/alert/index.ts
  app/_apis/application/index.ts
  app/_apis/shop/index.ts
  app/_apis/user/index.ts
  app/_components/blind-component/index.tsx
  app/_components/button/index.tsx
  app/_components/header/_component/_component/alert/alert-card.tsx
  app/_components/header/index.tsx
  app/_components/hydration/index.tsx
  app/_components/loading/loading.tsx
  app/_components/notice-card/_component/skeleton.tsx
  app/_components/notice-card/index.tsx
  app/_components/notice-detail-card/_component/notice-detail-card-skeleton.tsx
  app/_components/notice-detail-card/_component/register-button.tsx
  app/_components/notice-detail-card/index.tsx
  app/_components/notice-list/index.tsx
  app/_util/calculate-date-diff.ts
  app/_util/calculate-wage-percentage .ts
  app/_util/notice.ts
  app/_util/time-difference-from-now.ts
  app/actions/post-notice-action.ts
  app/layout.tsx
  app/page.tsx
  package.json
  stores/create-store.ts
Labels: ♻️ refactor

#127 🐛 fix: 페이지네이션 수정
  app/(route)/(alba)/layout.tsx
  app/_components/pagination/index.tsx
Labels: 🐛 fix

#129 🐛 fix: 로그아웃 쿠키 주소도 삭제
  app/_actions/index.ts
Labels: 🐛 fix

#134 feat: 프로필 편집 기능
  app/(route)/(alba)/@modal/(.)profile-edit/page.tsx
  app/(route)/(alba)/profile-detail/_components/user-profile/index.tsx
  app/(route)/(alba)/profile-edit/layout.tsx
  app/(route)/(alba)/profile-edit/page.tsx
  app/(route)/(alba)/profile-register/_components/form.tsx
  app/(route)/admin/shop-edit/page.tsx
  app/_apis/shop/index.ts
  app/_apis/type/index.ts
  app/_components/error-sign/index.tsx
Labels: ✨ feat

#137 ✨ feat: 가게 상세 페이지
  app/(route)/(alba)/notice-detail/[shop_id]/[notice_id]/page.tsx
  app/(route)/(alba)/notice-detail/_components/recent-notices/index.tsx
  app/(route)/(alba)/notice-list/_components/customized-notice/index.tsx
  app/(route)/(alba)/profile-detail/_components/user-profile/index.tsx
  app/(route)/admin/@modal/(.)shop-edit/page.tsx
  app/(route)/admin/shop-detail/_components/is-register-component/index.tsx
  app/(route)/admin/shop-detail/_components/my-shop-detail-card/index.tsx
  app/(route)/admin/shop-detail/_components/posted-notice/index.tsx
  app/(route)/admin/shop-detail/error.tsx
  app/(route)/admin/shop-detail/layout.tsx
  app/(route)/admin/shop-detail/page.tsx
  app/(route)/admin/shop-edit/error.tsx
  app/(route)/admin/shop-edit/page.tsx
  app/_apis/notice/index.ts
  app/_apis/shop/index.ts
  app/_apis/type/index.ts
  app/_apis/user/index.ts
  app/_components/header/_component/_component/alert/index.tsx
  app/_components/header/_component/header-login.tsx
  app/_components/interception-area/index.tsx
  app/_components/none-sign-button/index.tsx
  app/_components/notice-card/index.tsx
  app/_components/notice-list/index.tsx
Labels: ✨ feat

#152 ♻️ refactor: 맞춤공고 없을시 시급 높은 순으로 띄우기
  app/(route)/(alba)/notice-list/_components/need-login-section/index.tsx
  app/(route)/(alba)/notice-list/_components/need-profile-section/index.tsx
  app/(route)/(alba)/notice-list/page.tsx
  app/_apis/notice/index.ts
Labels: ♻️ refactor

#148 ♻️ refactor : 신청하기 선택 이후 리다이렉트 처리
  app/_components/notice-detail-card/_component/register-button.tsx
Labels: ♻️ refactor

#151 ✨ feat: 공고 편집 기능
  app/(route)/admin/@modal/(.)notice-create/_components/index.tsx
  app/(route)/admin/@modal/(.)notice-edit/[shop_id]/[notice_id]/page.tsx
  app/(route)/admin/@modal/(.)shop-create/page.tsx
  app/(route)/admin/layout.tsx
  app/(route)/admin/notice-detail/[shop_id]/[notice_id]/page.tsx
  app/(route)/admin/notice-edit/[shop_id]/[notice_id]/page.tsx
  app/_apis/notice/index.ts
Labels: ✨ feat

#153 ✨ feat: 정렬기준 추가
  app/(route)/(alba)/notice-list/_components/filter/index.tsx
  app/(route)/(alba)/notice-list/page.tsx
  app/_apis/notice/index.ts
  app/_components/header/_component/search.tsx
  app/_components/header/index.tsx
  app/_components/notice-list/_component/sort-drop-down.tsx
  app/_components/notice-list/index.tsx
  app/_util/get-tomorrow-midnight.ts
Labels: ✨ feat

#142 ♻️ refactor : 알림창 인터랙션 수정
  app/_components/header/_component/_component/alert/alert-card.tsx
  app/_components/header/_component/_component/alert/index.tsx
  app/_components/header/_component/header-login.tsx
  app/_components/header/_component/mockData.ts
Labels: ♻️ refactor

#155 🐛 fix: 모달 밖을 클릭해도 함수 실행 가능
  app/_components/modals/_components/confirm-modal.tsx
Labels: 🐛 fix

#160 ♻️ refactor: 사장 가게 소유자에 따른 화면 구현
  app/(route)/(alba)/notice-detail/[shop_id]/[notice_id]/page.tsx
  app/(route)/(alba)/notice-detail/_components/recent-notices/index.tsx
  app/(route)/(alba)/notice-list/page.tsx
  app/(route)/admin/notice-detail/[shop_id]/[notice_id]/page.tsx
  app/(route)/admin/shop-detail/_components/my-shop-detail-card/index.tsx
  app/(route)/admin/shop-detail/page.tsx
  app/_components/label-hourly-rate/index.tsx
  app/_components/notice-card/index.tsx
  app/_components/notice-detail-card/index.tsx
  app/_components/notice-list/index.tsx
  app/_components/only-label-hourly-rate/index.tsx
  app/_components/table/index.tsx
Labels: ♻️ refactor

#163 🐛 fix : 랜딩 페이지 document.querySelector == null 오류
  app/page.tsx
Labels: 🐛 fix

#167 🐛 fix : 공고 상세 취소하기 처리
  app/_components/header/_component/_component/alert/index.tsx
  app/_components/notice-detail-card/_component/register-button.tsx
Labels: 🐛 fix

#171 ♻️ refactor: 인풋 필수 추가 + 모달 모션 수정 + 토스트 위치 조정 + 토스트 에러 메시지 수정 + 토스트 디자인
  app/_apis/notice/index.ts
  app/_components/custom-date-input/index.tsx
  app/_components/custom-form-dropdown/index.tsx
  app/_components/custom-price-input/index.tsx
  app/_components/custom-text-input/index.tsx
  app/_components/custom-time-input/index.tsx
  app/_components/page-modal/index.tsx
  app/_util/notification.ts
Labels: ♻️ refactor

#169 ♻️ refactor: filter 가로 스크롤 제거 및 외부 클릭시 사라지게 수정
  app/(route)/(alba)/notice-list/_components/filter/index.tsx
  app/_apis/notice/index.ts
  app/_components/notice-list/index.tsx
  app/_util/get-thirty-minutes-later.ts
  app/_util/get-tomorrow-midnight.ts
  styles/globals.css
Labels: ♻️ refactor

#175 🐛 fix: 테이블 신청 모달 내용 수정
  app/(route)/admin/notice-detail/_components/status-label/index.tsx
Labels: 🐛 fix

#178 💄 ui: 버튼 로딩 달리는 사람
  app/(route)/(login)/login/login-form.tsx
  app/(route)/(login)/signup/sign-up-from.tsx
  app/(route)/admin/shop-create/shop-create-form.tsx
  app/(route)/admin/shop-edit/shop-edit-form.tsx
Labels: 💄ui

#182 ♻️ refactor : 배포를 위한 배포 파일 변경
  .github/workflows/deploy.yaml
Labels: ♻️ refactor

#184 🐛 Fix: 페이지네이션 에러, 상세필터와 정렬 연동에러 수정
  app/(route)/(alba)/notice-list/_components/filter/index.tsx
  app/(route)/(alba)/profile-detail/_components/notice-application-table/index.tsx
  app/(route)/(alba)/profile-detail/page.tsx
  app/(route)/admin/notice-detail/[shop_id]/[notice_id]/page.tsx
  app/_components/notice-list/_component/sort-drop-down.tsx
  app/_components/notice-list/index.tsx
Labels: 🐛 fix

#186 🐛 Fix: 인풋, 상세필터, 드롭다운 ui 수정
  app/(route)/(alba)/notice-list/_components/filter/index.tsx
  app/_components/header/_component/search.tsx
  app/_components/notice-list/_component/sort-drop-down.tsx
  app/_components/notice-list/index.tsx
  styles/globals.css
Labels: 🐛 fix

#188 🐛 fix: 테이블 사이즈 조절
  app/(route)/(alba)/profile-detail/_components/alba-status-label/index.tsx
Labels: 🐛 fix
